# Generated by Django 3.0.7 on 2020-06-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200603_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(choices=[('M', 'masculino'), ('F', 'feminino')], default=1, max_length=1, verbose_name='Sexo'),
            preserve_default=False,
        ),
    ]
