# Generated by Django 3.0.7 on 2020-06-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cliente_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estado',
            field=models.CharField(choices=[('n', 'novo'), ('u', 'usado'), ('r', 'recuperado')], default=1, max_length=1, verbose_name='Estado'),
            preserve_default=False,
        ),
    ]
