# Generated by Django 3.0.7 on 2020-06-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_produto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='m_ram',
            field=models.CharField(choices=[('256', 'DDR3 256MB'), ('512', 'DDR3 512MB'), ('1GB', 'DDR3 1GB'), ('2GB', 'DDR3 2GB'), ('4GB', 'DDR3 4GB'), ('8GB', 'DDR3 8GB'), ('16GB', 'DDR3 16GB')], default=1, max_length=10, verbose_name='Memoria Ram'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='pro_cessador',
            field=models.CharField(choices=[('core', 'core 2duo'), ('i3', 'core i3'), ('i5', 'core i5'), ('i7', 'core i7'), ('i9', 'core i9')], default=1, max_length=10, verbose_name='Processador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='storage',
            field=models.CharField(choices=[('128', '128 gb'), ('320', '320 gb'), ('500', '500 gb'), ('1', '1 tb'), ('2', '2 tb')], default=1, max_length=10, verbose_name='Armazenamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='tela',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, verbose_name='Tela'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='estado',
            field=models.CharField(choices=[('n', 'novo'), ('u', 'usado'), ('r', 'recuperado')], max_length=10, verbose_name='Estado'),
        ),
    ]
