# Generated by Django 3.0.7 on 2020-06-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200603_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tela',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Tela'),
        ),
    ]
