# Generated by Django 3.0.7 on 2020-07-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200603_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='estado',
            field=models.CharField(choices=[('novo', 'novo'), ('usado', 'usado'), ('recuperado', 'recuperado')], max_length=10, verbose_name='Estado'),
        ),
    ]
